[package]
name = "mips"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
defer = "0.2.1"
elf = "0.7.4"
rand = "0.8.5"
ratatui = "0.29.0"
